In [7]:
import pandas as pd
import json
df = pd.read_csv("locations.csv")
df

,MB2023_V1_00,LANDWATER,LANDWATER_NAME,LAND_AREA_SQ_KM,AREA_SQ_KM,Shape_Length,retrieved_at,n_POIs,bounds,centroid
0,100,12,Mainland,157.497825,157.497825,84526.158926,2023-08-24 11:37:18.041099,0,"172.6352435839961,-34.54863701565286,172.87829...","172.76733837985918,-34.478922829717746"
1,200,12,Mainland,120.503770,120.503770,122885.186789,2023-08-24 11:37:20.533876,0,"172.8542824170829,-34.52161633328387,173.05212...","172.94698170393258,-34.45655876543814"
2,300,12,Mainland,7.481859,7.481859,28321.227739,2023-08-24 11:37:20.538599,0,"172.84206983288533,-34.53278549976881,172.9225...","172.87976545025646,-34.50977846981489"
3,400,12,Mainland,83.342952,83.342952,41499.302475,2023-08-24 11:37:20.541395,0,"172.75759288462214,-34.6271183160912,172.89445...","172.8250443171708,-34.56058525557085"
4,1201,12,Mainland,51.238250,51.238250,62944.884996,2023-08-24 11:37:20.544155,1,"173.033969949182,-34.82551108204762,173.174736...","173.10101978845853,-34.75634587362149"
...,...,...,...,...,...,...,...,...,...,...
56783,4019154,12,Mainland,0.036001,0.036001,1105.893029,2023-08-24 18:08:22.089881,0,"174.80134530826163,-41.25386461779594,174.8048...","174.8032958014029,-41.252384905093116"
56784,4019155,12,Mainland,0.019734,0.019734,661.167326,2023-08-24 18:08:22.473459,0,"174.80181702413108,-41.25488188310054,174.8042...","174.80300326734843,-41.25396061008679"
56785,4019156,12,Mainland,0.097215,0.097215,1787.390321,2023-08-24 18:08:22.930917,6,"174.79049541680982,-41.26110144968412,174.7972...","174.79374495848225,-41.25827750871569"
56786,4019157,12,Mainland,0.066195,0.066195,1083.336705,2023-08-24 18:08:23.313995,4,"174.78636471703436,-41.2633821068233,174.79103...","174.78903872191805,-41.262061277837624"
56787,4010332,12,Mainland,39.690290,39.690290,37881.692754,2023-08-24 18:08:23.716513,1,"175.22159703278956,-40.34671240010535,175.3505...","175.27702575491014,-40.31981711839878"

In [4]:
df.n_POIs.value_counts(dropna=False)

0     32259
1     11334
2      4536
3      2241
4      1280
5       869
6       601
7       520
25      458
8       382
9       307
10      266
11      265
13      205
12      205
14      171
15      153
16      120
17      117
19      103
18      101
20       81
21       62
23       61
22       47
24       44
Name: n_POIs, dtype: int64

In [5]:
df.n_POIs.sum()

90597

In [8]:
with open("data.geojson") as f:
    geojson = json.load(f)
len(geojson["features"])

43354

In [12]:
pd.Series([str(r["properties"]["external_ids"].keys()) for r in geojson["features"]]).value_counts()

dict_keys(['foursquare'])                 38276
dict_keys(['foursquare', 'safegraph'])     2609
dict_keys(['safegraph', 'foursquare'])     2434
dict_keys([])                                32
dict_keys(['safegraph'])                      3
dtype: int64